### PR TITLE
[CMS PR 37811] SQL code style and consistency fixed and real null date for last_used

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for https://github.com/joomla/joomla-cms/pull/37811 .

### Summary of Changes

- Adjust code style in SQL scripts to the core.
- Have not null constraints and default values consistent between the 2 database types for the new table.
- Let data types, default values and not null constraints be consistent with the rest of the core.
- Do not use display width 1 for tinyint on MySQL since that does not serve any purpose and is deprecated in MySQL 8. See https://github.com/joomla/joomla-cms/pull/32606 for the explanation.
- Add the "CAN FAIL" installer hint to the update SQL script for PostgreSQL in case if the index already exists from a previous update attempt.
- Allow real null values for datetimes (here only the last_used).

### Testing Instructions

Code review.

### CODE REVIEW

**Comment by nikosdion** [comment]
Thanks! I made a small change to formatRelative to simplify the code in the view templates and committed it directly to my PR. Good call on adding JNEVER

**Comment by richard67** [comment]
I just see i have introduced a code style error. will propose fix in your pr.

**Comment by richard67** [comment]
Ah, no, I did not make any mistake. But why does it need all those `// phpcs:ignore`?

**Comment by nikosdion** [comment]
You did not make a mistake, this is an artefact of Joomla's coding standard. The coding standard says that you should never use `snake_case` variables, it demands they are always `camelCase`. However, this is absolutely impractical when you are interfacing database data where the convention is to always use `snake_case` column names.

There are two solutions to that.

1. Have a translation layer in the table **and all Models** converting snake_case to camelCase **consistently**. Problems: a. you need a hell of a lot of boilerplate code; b. it only takes one mistake to wreak havoc to the codebase and introduce major bugs that are hard to debug; c. it breaks the link between the code and the database, confusing the hell out of site integrators. Verdict: do not use.
2. Put a `// phpcs:ignore` comment on every line using a deliberately snake_case variable and groan internally. Verdict: frustrating as it is, it's the best solution.

**Pull request merged**
